---
# I store a lot of sensor data into InfluxDB, which allows me to query
# a longer history with ease. I use the Community Hass.io add-on for this,
# combined with the Community Hass.io Grafana add-on for the graphs.
#
# https://github.com/hassio-addons/addon-influxdb
# https://github.com/hassio-addons/addon-grafana
# https://www.home-assistant.io/components/influxdb/
#
influxdb:

  # This is the Hass.io add-on slug, allowing a direct connection to the addon.
  host: a0d7b954-influxdb
  port: 8086

  # The database name to store all the metrics in.
  database: homeassistant

  # Authentication credentials.
  username: !secret influxdb_username
  password: !secret influxdb_password

  # Max number of retries in case of a failure.
  max_retries: 3

  # The list of attribute names which should be reported as tags
  # and not fields to InfluxDB.
  # I've added `device_class` tag and the Z-Wave `node_id`.
  tags_attributes:
    - "device_class"
    - "node_id"

  # I like to specify (whitelist) each thing I'd like to put
  # into InfluxDB, to keep the database as clean as possible.
  include:
    entities:
      # Climate
      - binary_sensor.attic_boiler_burner
      - binary_sensor.attic_boiler_preheating
      - climate.bedroom_flynn
      - climate.bedroom_lilly
      - climate.bedroom_master
      - climate.living_room
      - sensor.attic_boiler_modulation_level
      - sensor.bathroom_humidity
      - sensor.bathroom_temperature

      # Energy
      - sensor.house_average_daily_gas_usage
      - sensor.house_average_daily_power_usage
      - sensor.house_average_gas_usage
      - sensor.house_average_power_usage
      - sensor.house_average_solar_production_to_grid
      - sensor.house_current_gas_usage
      - sensor.house_current_power_usage
      - sensor.house_current_solar_production
      - sensor.house_gas_meter
      - sensor.house_gas_usage_today
      - sensor.house_max_solar_production
      - sensor.house_power_meter_feed_in_tariff_1
      - sensor.house_power_meter_feed_in_tariff_2
      - sensor.house_power_meter_feed_out_tariff_1
      - sensor.house_power_meter_feed_out_tariff_2
      - sensor.house_power_usage_today
      - sensor.house_solar_production_to_grid

      # Infrastructure
      - sensor.infrastructure_adguard_average_processing_speed
      - sensor.infrastructure_adguard_dns_queries
      - sensor.infrastructure_adguard_dns_queries_blocked
      - sensor.infrastructure_adguard_dns_queries_blocked_ratio
      - sensor.infrastructure_adguard_parental_control_blocked
      - sensor.infrastructure_adguard_rules_count
      - sensor.infrastructure_adguard_safe_browsing_blocked

      # Other
      - binary_sensor.bathroom_hot_tap_water
