---
description: Close the hall curtain based on time or when the alarm arms
alias: hall_curtain_close
id: aefaa83e-9295-4b84-b33d-d53a377c8bd8
mode: ignore
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - alarm_control_panel.home_alarm
  - platform: time
    at: "19:00:00"
condition:
  - condition: or
    conditions:
      - condition: state
        entity_id:
          - alarm_control_panel.home_alarm
        state:
          - armed_away
          - armed_home
      - condition: time
        after: "19:00:00"
        before: "08:00:00"
action:
  - service: cover.close_cover
    data:
      entity_id:
        - cover.hall_curtain
