---
# Turns down bedroom heating on working days.
# We probably are up early so save some energy.
#
# On working days, we turn down the heating at 7AM,
# on other days, we might stay in bed a little longer, so 10AM in that case.
#
alias: bedroom_master_climate_low
trigger:
  - platform: time
    at: "07:00:00"
  - platform: time
    at: "10:00:00"
condition:
  - condition: or
    conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.workday
            state: "on"
          - condition: time
            before: '07:01:00'
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.workday
            state: "off"
          - condition: time
            after: '09:59:00'
action:
  service: climate.set_temperature
  data:
    entity_id: climate.bedroom_master
    temperature: 15
