---
# This automation turns off the thermostat in our master bedroom
# off in case the window is open, and on again when its closed.
#
# We have a 1 pump heating system and in the Netherlands you generally have
# only heating. On/Off for this is OK, since generally, I'm only changing
# temperatures.
#
alias: bedroom_master_window_climate
trigger:
  platform: state
  entity_id: binary_sensor.slaapkamer_raam
action:
  service: climate.set_operation_mode
  data_template:
    entity_id: climate.bedroom_master
    operation_mode: >-
      {% if is_state('binary_sensor.slaapkamer_raam', 'on') %}
        Off
      {% else %}
        Heat
      {% endif %}
