---
# Configuration for support-requests - https://github.com/dessant/support-requests

# Label used to mark issues as support requests
supportLabel: "Type: Support"

# Comment to post on issues marked as support requests. Add a link
# to a support page, or set to `false` to disable
supportComment: >
  :wave: We use the issue tracker exclusively for bug reports and feature requests.
  However, this issue appears to be a support request. For generic support or
  stuff, please get onto the Home Assistant community forum or Discord chat.

# Close issues marked as support requests
close: true

# Lock issues marked as support requests
lock: false
