---
# Entity configuration for Google Assistant.
#
# I use this to customize how the device shows up in Google Assistant.
#
# https://www.home-assistant.io/integrations/google_assistant/#entity_config
#
light.living_room_bar:
  name: Woonkamer Bar
  aliases:
    - woonkamer bar
    - bar
    - barretje
    - countertop
    - living room bar
    - onder de bar
    - under bar
  room: Woonkamer
