---
# When the alarm gets armed...
#
# Turn off the lights.
#
alias: kitchen_alarm_armed
trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: 'armed_away'
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: 'armed_home'
action:
  service: light.turn_off
  entity_id:
    - light.kitchen_ceiling
    - light.kitchen_cupboard
