---
alias: Kitchen Cupboard Light
description: >-
  Controls the light of the kitchen cupboard, based on the state of the
  kitchen ceiling light.

  If the kitchen ceiling light is set up brighter; it means something is going
  on in the kitchen (e.g., cooking, walk-in motions). In those cases, the
  lights of the cupboard can be switched on as well.

mode: single
id: 52e25b71-574b-40ae-b40c-69d9428f4dbe

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - light.kitchen_ceiling

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: light.kitchen_ceiling
            state: "on"
          - condition: numeric_state
            entity_id: light.kitchen_ceiling
            attribute: brightness
            above: 115
        sequence:
          - service: switch.turn_on
            target:
              entity_id: switch.kitchen_cupboard
    default:
      - service: switch.turn_off
        target:
          entity_id: switch.kitchen_cupboard
