---
alias: Kitchen Lights Off
description: >-
  Turn lights off in our kitchen when the alarm is armed.

id: 158fc336-81b5-4ba1-b060-fee6192d9c7d

use_blueprint:
  path: alarm_armed_lights_off.yaml
  input:
    lights:
      area_id: kitchen
