---
# This automation turns off the thermostat in our Flynn's bedroom
# off in case the window is open, and on again when its closed.
#
# We have a 1 pump heating system and in the Netherlands you generally have
# only heating. On/Off for this is OK, since generally, I'm only changing
# temperatures.
#
alias: bedroom_flynn_window_climate
trigger:
  platform: state
  entity_id: binary_sensor.bedroom_flynn_window
action:
  service: climate.set_hvac_mode
  data_template:
    entity_id: climate.bedroom_flynn
    operation_mode: >-
      {% if is_state('binary_sensor.bedroom_flynn_window', 'on') %}
        Off
      {% else %}
        Heat
      {% endif %}
