---
# Light group: Bathroom
#
# https://www.home-assistant.io/integrations/light.group/
#
platform: group
name: bathroom
entities:
  - light.bathroom_ceiling_1
  - light.bathroom_ceiling_2
  - light.bathroom_ceiling_3
