---
# Light group: Garden Veranda
#
# Combines all lights in the garden veranda into a single entity.
#
# https://www.home-assistant.io/integrations/light.group/
#
platform: group
name: garden_veranda
entities:
  - light.garden_veranda_wall_left
  - light.garden_veranda_wall_right
  - light.garden_veranda_wall_shed
