---
# Light group: Garden Border
#
# A light group to combine all garden border lights into a single entity.
#
# https://www.home-assistant.io/integrations/light.group/
#
platform: group
name: garden_border
entities:
  - light.garden_border_back_left
  - light.garden_border_back_right
  - light.garden_border_front
