---
# Light group: Garden
# We have a wall on the left and right of our garden.
# Both have a Philips Hue light, which we control as one.
#
# Other lights needs to be replaced and hooked up.
#
# https://www.home-assistant.io/integrations/light.group/
#
platform: group
name: garden
entities:
  - light.garden_border_back_left
  - light.garden_border_back_right
  - light.garden_border_front
  - light.garden_dining_table
  - light.garden_veranda_wall_left
  - light.garden_veranda_wall_right
  - light.garden_veranda_wall_shed
  - light.garden_wall_left
  - light.garden_wall_right
