---
# Light group: Living Room Window
#
# This light group combines my window lights into a single entity
#
# https://www.home-assistant.io/integrations/light.group/
#
platform: group
name: living_room_window
entities:
  - light.living_room_window_1
  - light.living_room_window_2
  - light.living_room_window_3
  - light.living_room_window_4
  - light.living_room_window_5
