---
# Light group: Office Window
#
# This light group combines my office window lights into one.
#
# https://www.home-assistant.io/integrations/light.group/
#
platform: group
name: office_window
entities:
  - light.office_window_1
  - light.office_window_2
