---
# We own a couple of Xiaomi/Yeelight bedside lamps.
#
# https://www.home-assistant.io/integrations/light.yeelight/
#
!secret yeelight_master_bedroom_bedside_daphne_host:
  name: master_bedroom_bedside_daphne
  transition: 2500
  use_music_mode: false
  save_on_change: false
