---
# When the alarm gets armed...
#
# Turn off the lights
#
alias: restroom_alarm_armed
initial_state: true
trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: 'armed_away'
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: 'armed_home'
action:
  - service: light.turn_off
    data:
      entity_id:
        - light.restroom
