---
# Simple automation, that turns the lights on as
# soon as someone enters our downstairs little room.
#
alias: restroom_motion_lights_on
trigger:
  platform: state
  entity_id: binary_sensor.restroom_motion
  to: 'on'
action:
  service: light.turn_on
  data:
    transition: 2
    brightness: 50
    entity_id:
      - light.restroom
