---
# Simple automation, that turns the lights off as
# soon as someone has left our downstairs little room.
#
alias: restroom_motion_lights_off
trigger:
  platform: state
  entity_id: binary_sensor.restroom_motion
  to: 'off'
  for:
    minutes: 1
action:
  service: light.turn_off
  entity_id: light.restroom
