---
# Turns up the heating in Lilly's bedroom, so it is nice when she
# goes to bed at 7PM.
#
alias: bedroom_lilly_climate_high
trigger:
  platform: time
  at: "17:30:00"
action:
  service: climate.set_temperature
  data:
    entity_id: climate.bedroom_lilly
    temperature: 19
