---
description: Turn lights off in our master bedroom
alias: bedroom_master_lights_off
id: 0f0252c0-61af-4090-9ff2-5531e089cba4
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - alarm_control_panel.home_alarm
condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state:
      - armed_away
      - armed_home
action:
  - service: light.turn_off
    data:
      entity_id:
        - light.bedroom_master
      transition: 5
