---
# Turns on the doorbell chime in the morning
# and the later afternoon. At these times,
# our kids are awake for sure.
#
alias: porch_doorbell_chime_on
trigger:
  - platform: time
    at: "07:30:00"
  - platform: time
    at: "15:00:00"
action:
  service: switch.turn_on
  entity_id: switch.porch_doorbell
