---
description: Turns the doorbell chime on when the kids are awake.
alias: porch_doorbell_chime_on
id: 874e3632-6a9c-4470-9563-7fe28ce068f7
mode: queue
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: template
    value_template: >-
      {{
        states('input_datetime.house_silent_hours_end')
        ==
        states('sensor.time')+":00"
      }}
action:
  - service: switch.turn_on
    data:
      entity_id:
        - switch.porch_doorbell_chime
