---
# This automation is my Doorbell replacement
#
# I use an Xiaomi Switch (the round ones) for this.
# When pressed, we send out some notifications.
#
alias: porch_doorbell
trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.doorbell
      click_type: single
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.doorbell
      click_type: doubled
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.doorbell
      click_type: long_click_press
action:
  - service: notify.ios_francks_iphone
    data:
      title: Deurbell
      message: Ding dong! Er staat iemand aan de deur!
      data:
        attachment:
          content-type: jpeg
          url: http://tiptag.com.ar/wp-content/uploads/2018/06/timbre1.jpg
  - service: notify.ios_daphne_iphone
    data:
      title: Deurbell
      message: Ding dong! Er staat iemand aan de deur!
      data:
        attachment:
          content-type: jpeg
          url: http://tiptag.com.ar/wp-content/uploads/2018/06/timbre1.jpg
  - service: xiaomi_aqara.play_ringtone
    data:
      gw_mac: !secret xiaomi_aqara_livingroom_mac
      ringtone_id: 10
      ringtone_vol: 8
