---
# Turns on the doorbell chime in the morning
# and the later afternoon. At these times,
# our kids are awake for sure.
#
alias: porch_doorbell_chime_on
trigger:
  - platform: template
    value_template: >-
      {{
        states('input_datetime.house_silent_hours_end')
        ==
        states('sensor.time')+":00"
      }}
  - platform: template
    value_template: >-
      {{
        states('input_datetime.person_flynn_nap_end')
        ==
        states('sensor.time')+":00"
      }}
action:
  service: switch.turn_on
  entity_id: switch.porch_doorbell
