---
description: Turns the doorbell chime off when kids are sleeping
alias: porch_doorbell_chime_off
id: e7313dd1-3776-4740-9888-d7f15cf33158
mode: queued
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: time
    at: input_datetime.house_silent_hours_start
action:
  - service: switch.turn_off
    data:
      entity_id:
        - switch.porch_doorbell_chime
