---
# Turns off the doorbell chime in the evening
# and at the afternoon. At these times, we
# have kids that sleep.
#
alias: porch_doorbell_chime_off
trigger:
  - platform: template
    value_template: >-
      {{ 
        states('input_datetime.house_silent_hours_start')
        ==
        states('sensor.time')+":00"
      }}
  - platform: template
    value_template: >-
      {{
        states('input_datetime.person_flynn_nap_start')
        ==
        states('sensor.time')+":00"
      }}
action:
  service: switch.turn_off
  entity_id: switch.porch_doorbell
