---
#
# Customizes the living window lights in Home Assistant
#
# https://www.home-assistant.io/docs/configuration/customizing-devices/
#
light.living_room_window:
  icon: mdi:window-maximize
  friendly_name: Living Room Window
