---
#
# Customizes the bedside light for Frenck in Home Assistant
#
# https://www.home-assistant.io/docs/configuration/customizing-devices/
#
light.bedroom_master_bedside_frenck:
  friendly_name: Master Bedroom Bedside Frenck
  icon: mdi:weather-night
