---
# When it is getting dark outside...
#
alias: garden_sunset
trigger:
  platform: sun
  event: sunset
  offset: '-00:15:00'
action:
  - service: light.turn_on
    entity_id: light.garden_wall
  - service: switch.turn_on
    entity_id: switch.circadian_lighting_garden_circadian_lighting
