---
id: 78d0de69-fa4e-4c59-8440-31db1b708297
alias: attic_ventilation_speed_medium
description: Controls the speed of the central ventilation system
trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id:
      - fan.attic_ventilation
      - sensor.bathroom_humidity
      - switch.attic_ventilation_manual_mode
  - platform: state
    entity_id: light.restroom
    to: 'off'
    for:
      minutes: 10
condition:
  - condition: state
    entity_id: switch.attic_ventilation_manual_mode
    state: 'off'
  - condition: numeric_state
    entity_id: sensor.bathroom_humidity
    above: 70
    below: 80
  - condition: state
    entity_id: light.restroom
    state: 'off'
    for:
      minutes: 10
action:
  - service: fan.turn_on
    entity_id:
      - fan.attic_ventilation
  - service: fan.set_speed
    entity_id:
      - fan.attic_ventilation
    data:
      speed: medium
