---
# When the alarm gets armed away, we've left the home.
#
# Run the vacuum cleaner if it has not ran the past 4 hours
#
alias: living_room_alarm_armed_away_vacuum
trigger:
  platform: state
  entity_id: alarm_control_panel.home_alarm
  to: 'armed_away'
condition:
  condition: state
  entity_id: vacuum.living_room
  state: 'docked'
  for:
    hours: 4
action:
  - service: vacuum.start
    entity_id: vacuum.living_room
  - service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.living_room
      fan_speed: 'Max'
