---
# When the alarm gets armed...
# Turn down the heating, lights and other devices.
#
alias: living_room_alarm_armed
initial_state: true
trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: 'armed_away'
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: 'armed_home'
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.living_room
      temperature: 15
  - service: light.turn_off
    data:
      entity_id:
        - light.living_room_bar
        - light.living_room_spotlight
        - light.living_room_window
        - light.living_room_television
  - service: media_player.turn_off
    data:
      entity_id:
        - media_player.living_room_shield
        - media_player.living_room_shield_android
