---
# When the alarm gets disarmed, ensure the vacuum cleaner is docked.
#
# We don't want that thing to be in our way when home.
#
alias: living_room_alarm_disarmed_vacuum
initial_state: true
trigger:
  platform: state
  entity_id: alarm_control_panel.home_alarm
  to: 'disarmed'
condition:
  condition: state
  entity_id: vacuum.living_room
  state: 'cleaning'
action:
  service: vacuum.return_to_base
  entity_id: vacuum.living_room
