---
# Turns off my heating way before bedtime.
#
alias: living_room_climate_late_night_off
trigger:
  platform: time
  at: "22:00:00"
action:
  service: climate.set_temperature
  data:
    entity_id: climate.living_room
    temperature: 15
