---
alias: Living Room Lights Sunlight
description: >-
  This automation triggers quite a bit. If the lights are on, the lights
  in the living room (that are on) are automatically adjusted to a sunlight
  rithm kinda light.

  This causes the lights in our living room to always be nice to the eyes.

id: 71758513-61f3-47f5-a7f0-7df5bb2f8de8
mode: queued

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - input_boolean.living_room_automatic_lighting
      - sensor.garden_luminosity
  - platform: time_pattern
    minutes: 5

condition:
  - condition: state
    entity_id:
      - input_boolean.living_room_automatic_lighting
    state: "on"

action:
  - service: script.sunlight
    data:
      entities:
        - light.living_room
