---
# Turn on the LED strip underneath the living room television when the
# media player is turned on.
#
# 99% of our TV time, is using the NVidia Shield, so that is an awesome
# device to trigger on.
#
alias: livingroom_theater_lights_on
initial_state: true
trigger:
  - platform: state
    entity_id: media_player.livingroom_shield
    from: 'off'
  - platform: state
    entity_id: media_player.living_room_shield_android
    from: 'off'
action:
  service: light.turn_on
  data:
    entity_id: light.livingroom_tv
    brightness_pct: 75
    rgb_color: [255, 255, 255]
    transition: 5
