---
# esp06: Yet unused Sonoff POW R2
#
# This ESPHome code is used on a Sonoff POW R2.
# It is used to detect if my Dryer is running.
# It exposes a lot of information, including an
# additional binary sensor. This allows easy
# automations from Home Assistant.
#
esphome:
  name: esp06
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: !secret wifi_not_ssid
  password: !secret wifi_not_password

logger:
  # Disable the Serial interface on the POW
  # It is used by the power sensor
  baud_rate: 0

# Enable UART for the power sensor
uart:
  rx_pin: RX
  baud_rate: 4800

api:
  password: !secret esphome_esp06_api_password

ota:
  password: !secret esphome_esp06_ota_password

web_server:
  port: 80

sensor:
  - platform: wifi_signal
    name: esphome_esp06_wifi_signal
    update_interval: 10s
  - platform: uptime
    name: esphome_esp06_uptime
  - platform: cse7766
    update_interval: 5s
    current:
      name: scullery_dryer_current
    voltage:
      name: scullery_dryer_voltage
    power:
      id: power
      name: scullery_dryer_power

text_sensor:
  - platform: version
    name: esphome_esp06_esphome_version

switch:
  - platform: restart
    name: esphome_esp06_restart
  # This is the actual exposed power switch
  - platform: gpio
    name: scullery_dryer
    id: relay
    pin: GPIO12
    restore_mode: ALWAYS_ON
    on_turn_on:
      - light.turn_on: led
    on_turn_off:
      - light.turn_off: led

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - switch.toggle: relay
  # This binary sensor tells if the Dryer is powered on itself (display)
  - platform: template
    name: scullery_dryer_on
    filters:
      - delayed_off: 10s
    lambda: |-
      return id(power).state > 2;
  # This binary sensor tells if the Dryer is running or not
  - platform: template
    name: scullery_dryer_running
    filters:
      - delayed_off: 15s
    lambda: |-
      return id(power).state > 75;

output:
  - platform: esp8266_pwm
    id: blue_led
    pin:
      number: GPIO13
      inverted: true

light:
  - platform: monochromatic
    output: blue_led
    id: led
