---
# When the alarm gets armed...
#
# Turn off the lights
#
alias: landing_alarm_armed
trigger:
  platform: state
  entity_id: alarm_control_panel.home_alarm
  to: 'armed_away'
action:
  service: light.turn_off
  entity_id: light.landing_ceiling
