---
alias: Landing Lights Off
description: >-
  Turn lights off on our landing when the alarm is armed.

id: 5ba4c940-2fb0-4a87-9761-d8c00c892189

use_blueprint:
  path: alarm_armed_lights_off.yaml
  input:
    lights:
      area_id: landing
