---
# When the alarm gets armed away...
#
# Make sure the lights are off
#
alias: bathroom_alarm_armed_away
trigger:
  platform: state
  entity_id: alarm_control_panel.home_alarm
  to: 'armed_away'
action:
  service: light.turn_off
  entity_id: light.bathroom_ceiling
