---
alias: bathroom_lights_off
id: c50e3d67-c377-40e6-aefa-9ea679efa603
description: Turn lights off in our bathroom when the alarm is armed
trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id:
      - alarm_control_panel.home_alarm
condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_away
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_home
action:
  - service: light.turn_off
    entity_id:
      - light.bathroom
    data:
      transition: 5
