name: Home Assistant CI

on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * *

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Copy stub files into configuration folder
        run: cp -R ./.stubs/* ./config
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:latest"
        with:
          args: |
            python -m homeassistant --version
      - name: Home Assistant Check
        uses: "docker://homeassistant/home-assistant:latest"
        with:
          args: |
            python -m homeassistant \
              --config ./config/ \
              --script check_config \
              --info all
